# Generated by Django 4.1.7 on 2023-03-28 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApostilList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО заявителя')),
                ('count_docs', models.PositiveIntegerField(default=1, verbose_name='Количество документов')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('is_done', models.BooleanField(default=False, help_text='Признак окончания обслуживания', verbose_name='Услуга предоставлена')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('time', models.TimeField(choices=[(datetime.time(9, 0), '9:00'), (datetime.time(9, 30), '9:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30')], null=True, verbose_name='Время приема')),
                ('apostil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apostil', to='apostil.apostillist')),
            ],
            options={
                'verbose_name': 'Дата время приема',
                'verbose_name_plural': 'Даты время приема',
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.AddField(
            model_name='apostillist',
            name='chunk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='apostil.chunk'),
        ),
    ]
