# Generated by Django 4.1.7 on 2023-03-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apostil', '0002_remove_apostillist_chunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='apostil',
        ),
        migrations.AddField(
            model_name='apostillist',
            name='chunk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='apostil.chunk'),
        ),
    ]
