# Generated by Django 4.1.7 on 2023-04-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apostil', '0003_remove_chunk_apostil_apostillist_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostillist',
            name='is_gone',
            field=models.BooleanField(default=False, verbose_name='Не явились'),
        ),
        migrations.AlterField(
            model_name='apostillist',
            name='chunk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='apostil.chunk', verbose_name='Слот времени'),
        ),
        migrations.AlterField(
            model_name='apostillist',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Документы предоставлены'),
        ),
    ]
