# Generated by Django 4.2 on 2023-04-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apostil', '0004_apostillist_is_gone_alter_apostillist_chunk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apostillist',
            options={'ordering': ['-chunk'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='apostillist',
            name='chunk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apostils', to='apostil.chunk', verbose_name='Слот времени'),
        ),
    ]
