# Generated by Django 4.1.7 on 2023-04-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostil', '0005_alter_apostillist_options_alter_apostillist_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostillist',
            name='executor_name',
            field=models.CharField(blank=True, choices=[('Морозова Елена Ивановна', 1), ('Козина Екатерина Витальевна', 2), ('Плеханова Ольга Александровна ', 3)], max_length=100, null=True, verbose_name='Исполнитель'),
        ),
    ]
