# Generated by Django 4.1.7 on 2023-04-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostil', '0006_apostillist_executor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostillist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления'),
        ),
        migrations.AlterField(
            model_name='apostillist',
            name='executor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Исполнитель'),
        ),
    ]
