# Generated by Django 4.2 on 2023-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostil', '0007_apostillist_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostillist',
            name='finish_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи документов'),
        ),
        migrations.AddField(
            model_name='apostillist',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='Признак выдачи документов'),
        ),
    ]
